version: '3.1'

services:
  mysql:
    image: mysql:latest
    ports:
      - "8000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
